### ISSUE TITLE
Future development?

### ISSUE THREAD

**Issue by Thomas-Moore-Creative** [oceanhackweek/ohw20-proj-marine-heat-waves#1]
Hello OHW MHW project team, 
(@cgentemann, @NickMortimer, @ocefpaf, et al )

Can I ask how far along you folks progressed on the goal of taking E. Oliver Marine Heat Waves (MHW) code and refactoring to take advantage of xarray, datetime, and dask?

Assuming it still needs work to be generalised for public use should others jump aboard this effort?  Or start from scratch?  Is there a list of issues to tackle?  Thanks!

**Comment by cgentemann** [comment]
Hi! we are scheduling a meeting to organize on github issues to address.  We would love to have you help out!

**Comment by Thomas-Moore-Creative** [comment]
Thanks for a great chat!
