### ISSUE TITLE
Set up repository as a python package

### ISSUE THREAD

**Issue by NickMortimer** [oceanhackweek/ohw20-proj-marine-heat-waves#6]
The repository currently is a collection of user-contributed notebooks that include code, this code needs to be split out into a package and the notebooks need to reference that package.

@cgentemann what should we call this package?  HeatWaveXR?

**Comment by NickMortimer** [comment]
Ok I've changed the dir structure (it could be further refined) I have split the climatology code out into heatwavexr.py and it can now be installed as a package using pip

**Comment by Thomas-Moore-Creative** [comment]
Heya @NickMortimer , great effort.  An ignorant question: do we need to decide on package name or make it “pip-able” before we have the working functions written?  Might we find we are best placed to make decisions on how to structure the package after we have working, defined functions?

I'm still getting my head around the good work y'all have done - does the new structure take into account some of Eric Oliver's points in his earlier email to you?

> “the climatology/threshold calculation could be easily made into an array operation [and in fact I would like to see this pulled out as a separate function for non-MHW uses]”

**Comment by NickMortimer** [comment]
Ok yes, basically if you want to pip it then it needs a name that you use in the import statement eg.

Import heatwavexr as hw

And yes the R version split up the functions as Eric suggested so my aim was to make the function names the same as the R version where appropriate


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
